sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull tomdesinto/testcafe:latest

script:
- docker run --rm -t -v $(pwd)/tests/:/tests tomdesinto/testcafe:latest testcafe 'chromium --no-sandbox,firefox' '/tests/*.test.js'